# 获取所有用户
GET http://localhost:8080/users

# 获取 root
GET http://localhost:8080/users/role/root

# 获取 id == 10001 的用户
GET http://localhost:8080/users/10001

# 获取 username == root 的用户
GET http://localhost:8080/users/username/root


# 添加 Root 用户
POST http://localhost:8080/users/root
Content-Type: application/json

{
  "username": "root2",
  "password": "root2"
}


# 添加 Admin 用户
POST http://localhost:8080/users/admin
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


# 添加 Staff 用户
POST http://localhost:8080/users/staff
Content-Type: application/json

{
  "username": "staff",
  "password": "staff"
}


# 添加 Client 用户
POST http://localhost:8080/users/client
Content-Type: application/json

{
  "username": "client",
  "password": "client",
  "companyName": "company",
  "phoneNumber": "1234567890"
}