@base_url = http://localhost:8080/users

### admin 登陆
POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### 获取所有用户
GET {{base_url}} HTTP/1.1


### 获取 client 用户列表
GET {{base_url}}/role/client HTTP/1.1


### 获取 id == 20001 的用户
GET {{base_url}}/20001 HTTP/1.1


### 获取 username == staff 的用户
GET {{base_url}}/username/staff HTTP/1.1


### 添加 client 用户
POST {{base_url}}/client HTTP/1.1
Content-Type: application/json

{
    "username": "client1",
    "password": "client1",
    "companyName": "company1",
    "phoneNumber": "12345678901"
}


### 查看当前用户是否登陆
GET {{base_url}}/status HTTP/1.1


### 查看当前用户信息
GET {{base_url}}/current HTTP/1.1


### 冻结 / 解冻 30001
PATCH {{base_url}}/30001/active HTTP/1.1


### 更新用户信息
PUT {{base_url}} HTTP/1.1
Content-Type: application/json

{
    "userId": 40001,
    "username": "clientest",
    "companyName": "acaasdada",
    "phoneNumber": "123413155678901"
}


### 修改用户密码
PATCH {{base_url}}/password HTTP/1.1
Content-Type: application/json

{
    "userId": 40001,
    "oldPassword": "client",
    "newPassword": "test"
}